config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  resources :images, only: [:index, :show, :new, :create, :destroy]

  # Defines the root path route ("/")
  root "images#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/image.rb
class Image < ApplicationRecord
  mount_uploader :img_file, ImgFileUploader

  validates :title, :description, :img_file, :uploaded_at, presence: true

  def time_since_upload
    elapsed_time = Time.now - self.uploaded_at

    case elapsed_time
    when 0..59
      "#{elapsed_time.to_i} seconds ago"
    when 60..3599
      "#{(elapsed_time / 60).to_i} minutes ago"
    when 3600..7199
      "1 hour ago"
    when 7200..86399
      "#{(elapsed_time / 3600).to_i} hours ago"
    when 86400..172799
      "1 day ago"
    when 172800..31535999
      "#{(elapsed_time / 86400).to_i} days ago"
    when 31536000..63071999
      "1 year ago"
    else
      "#{(elapsed_time / 31536000).to_i} years ago"
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  def index
    @images = Image.all.order(uploaded_at: :desc)
  end

  def show
    @image = Image.find(params[:id])
  end

  def new
    @image = Image.new
  end

  def create
    @image = Image.new(image_params)
    @image.uploaded_at = Time.now

    if @image.save
      redirect_to @image, notice: 'Image uploaded successfully.'
    else
      flash[:alert] = @image.errors.full_messages.to_sentence
      render :new
    end
  end

  def destroy
    @image = Image.find(params[:id])
    @image.destroy
    redirect_to images_path, notice: 'Image was successfully deleted.'
  end

  private

  def image_params
    params.require(:image).permit(:title, :description, :img_file)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/index.html.erb
<main class="py-5 bg-body-tertiary">
  <div class="container">
    <div class="row row-cols-1 row-cols-sm-2 row-cols-md-3 g-3 justify-content-center align-items-stretch">
      <% @images.each do |image| %>
        <div class="col d-flex">
          <div class="card shadow-sm flex-fill">
            <%= image_tag(image.img_file.url, class: 'card-img-top cover', height: '300', width: '300') if image.img_file? %>

            <div class="card-body d-flex flex-column">
              <h5 class="card-title"><%= image.title %></h5>
              <p class="card-text"><%= truncate(image.description, length: 90) %></p>
              <div class="mt-auto d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%= link_to 'View', image_path(image), class: 'btn btn-sm btn-outline-secondary' %>
                  <%= link_to 'Delete', image_path(image), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-sm btn-outline-danger' %>
                </div>
                <small class="text-body-secondary"><%= image.time_since_upload %></small>
              </div>
            </div>

          </div>
        </div>
      <% end %>
    </div>
  </div>
</main>

app/views/images/new.html.erb
<main class="pt-3 bg-body-tertiary">
  <div class="w-75 mx-auto">
    <div class="d-flex justify-content-between align-items-center my-2">
      <h1 class="ms-4">Upload New Image</h1>
      <div class="d-flex justify-content-end me-4">
        <%= link_to 'Back to Gallery', images_path, class: 'btn btn-secondary' %>
      </div>
    </div>
    <%= form_with model: @image, local: true, html: { multipart: true }, class: 'w-50 mx-auto mt-5' do |form| %>
      <div class="form-group">
        <%= form.label :title %>
        <%= form.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group mt-1">
        <%= form.label :description %>
        <%= form.text_area :description, class: 'form-control' %>
      </div>

      <div class="form-group mt-1">
        <%= form.label :img_file %>
        <%= form.file_field :img_file, class: 'form-control' %>
      </div>

      <div class="w-100 d-flex justify-content-end">
        <%= form.submit 'Upload', class: 'btn btn-primary mt-3 me-0' %>
      </div>
    <% end %>
  </div>
</main>

app/views/images/show.html.erb
<main class="pb-5 pt-2 bg-body-tertiary">
  <div class="d-flex justify-content-between align-items-center my-2">
    <h1 class="ms-4"><%= @image.title %></h1>
    <div class="d-flex justify-content-end me-4">
      <%= link_to 'Back to Gallery', images_path, class: 'btn btn-secondary' %>
    </div>
  </div>

  <div class="w-100 d-flex justify-content-center">
    <% if @image.img_file.url.present? %>
      <%= image_tag( @image.img_file.url, class: 'img-fluid') %>
    <% else %>
      <p>No image available</p>
    <% end %>
  </div>

  <div class="mt-3">
    <p class="mx-4"><%= @image.description %></p>
    <div class="d-flex justify-content-between align-items-center my-2 mx-5">
      <div class="d-flex justify-content-end me-4">
        <%= link_to 'Delete', image_path(@image), method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger me-3' %>
        <%= link_to 'Back to Gallery', images_path, class: 'btn btn-secondary' %>
      </div>
      <p>Uploaded at: <%= @image.uploaded_at.strftime('%d/%m/%Y - %H:%Mh') %></p>
    </div>
  </div>
</main>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PhotoVisor</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <header class="d-flex justify-content-between align-items-center my-2">
      <h1 class="ms-3">Photo Visor</h1>
      <div class="d-flex justify-content-end me-3">
        <%= link_to 'Upload New Image', new_image_path, class: 'btn btn-outline-secondary btn-sm' %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>